import { League, Team, Player, Game, StatEvent, StaffUser } from "./types";

export const INITIAL_LEAGUES: League[] = [
  {
    id: "d2l-s10",
    name: "District 2 League (D2L)",
    season: "Season 10 - 2026",
    location: "Ayala Alabang Village Main Gym, Muntinlupa City",
    isActive: true,
  },
  {
    id: "aav-masters-2026",
    name: "Ayala Alabang Invitational Cup",
    season: "Summer 2026",
    location: "Cuenca Community Center Court",
    isActive: false,
  },
];

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: "staff-1",
    name: "Marcus Alcantara",
    email: "marcus@d2league.ph",
    role: "admin", // System Admin: full access
    pin: "2026",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "staff-2",
    name: "Dave Santos",
    email: "dave@d2league.ph",
    role: "staff", // Staff: courtside live tracking only
    pin: "1234",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-titans",
    leagueId: "d2l-s10",
    name: "Alabang Titans",
    shortName: "TITANS",
    logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#0B3B24",
    secondaryColor: "#D4AF37",
    wins: 7,
    losses: 1,
    pointsFor: 688,
    pointsAgainst: 602,
    streak: "W4",
  },
  {
    id: "team-vipers",
    leagueId: "d2l-s10",
    name: "Cuenca Vipers",
    shortName: "VIPERS",
    logo: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#1A365D",
    secondaryColor: "#FF6B00",
    wins: 6,
    losses: 2,
    pointsFor: 672,
    pointsAgainst: 618,
    streak: "W2",
  },
  {
    id: "team-knights",
    leagueId: "d2l-s10",
    name: "Narra Knights",
    shortName: "KNIGHTS",
    logo: "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#581C87",
    secondaryColor: "#F59E0B",
    wins: 5,
    losses: 3,
    pointsFor: 640,
    pointsAgainst: 630,
    streak: "L1",
  },
  {
    id: "team-ballers",
    leagueId: "d2l-s10",
    name: "Palms Ballers",
    shortName: "BALLERS",
    logo: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#065F46",
    secondaryColor: "#10B981",
    wins: 4,
    losses: 4,
    pointsFor: 612,
    pointsAgainst: 620,
    streak: "W1",
  },
  {
    id: "team-aces",
    leagueId: "d2l-s10",
    name: "Acacia Aces",
    shortName: "ACES",
    logo: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#831843",
    secondaryColor: "#E2E8F0",
    wins: 3,
    losses: 5,
    pointsFor: 590,
    pointsAgainst: 615,
    streak: "L2",
  },
  {
    id: "team-heat",
    leagueId: "d2l-s10",
    name: "Country Club Heat",
    shortName: "HEAT",
    logo: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#991B1B",
    secondaryColor: "#FBBF24",
    wins: 2,
    losses: 6,
    pointsFor: 575,
    pointsAgainst: 640,
    streak: "L3",
  },
  {
    id: "team-kings",
    leagueId: "d2l-s10",
    name: "Champaca Kings",
    shortName: "KINGS",
    logo: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#312E81",
    secondaryColor: "#A78BFA",
    wins: 5,
    losses: 1,
    pointsFor: 490,
    pointsAgainst: 420,
    streak: "W5",
  },
  {
    id: "team-gunners",
    leagueId: "d2l-s10",
    name: "Ridge Gunners",
    shortName: "GUNNERS",
    logo: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#134E4A",
    secondaryColor: "#2DD4BF",
    wins: 4,
    losses: 2,
    pointsFor: 468,
    pointsAgainst: 445,
    streak: "W1",
  },
];

export const INITIAL_PLAYERS: Player[] = [
  // --- TITANS ROSTER ---
  {
    id: "p-titans-34",
    teamId: "team-titans",
    jerseyNumber: 34,
    name: "Brian Moore",
    firstName: "Brian",
    lastName: "Moore",
    position: "C",
    height: "6'6\"",
    weight: "225 lbs",
    age: 29,
    hometown: "Ayala Alabang (Narra St.)",
    photoUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-titans-7",
    teamId: "team-titans",
    jerseyNumber: 7,
    name: "Kiefer Reyes",
    firstName: "Kiefer",
    lastName: "Reyes",
    position: "PG",
    height: "5'11\"",
    weight: "175 lbs",
    age: 26,
    hometown: "Ayala Alabang (Cuenca)",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-titans-23",
    teamId: "team-titans",
    jerseyNumber: 23,
    name: "Marcus Alcantara",
    firstName: "Marcus",
    lastName: "Alcantara",
    position: "SG",
    height: "6'2\"",
    weight: "190 lbs",
    age: 28,
    hometown: "Ayala Alabang (Acacia St.)",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-titans-11",
    teamId: "team-titans",
    jerseyNumber: 11,
    name: "Dave Santos",
    firstName: "Dave",
    lastName: "Santos",
    position: "SF",
    height: "6'3\"",
    weight: "198 lbs",
    age: 27,
    hometown: "Ayala Alabang (Champaca St.)",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-titans-15",
    teamId: "team-titans",
    jerseyNumber: 15,
    name: "Anton Castillo",
    firstName: "Anton",
    lastName: "Castillo",
    position: "PF",
    height: "6'4\"",
    weight: "210 lbs",
    age: 31,
    hometown: "Ayala Alabang (Tindalo St.)",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-titans-3",
    teamId: "team-titans",
    jerseyNumber: 3,
    name: "Gelo Ramos",
    firstName: "Gelo",
    lastName: "Ramos",
    position: "PG",
    height: "5'9\"",
    weight: "165 lbs",
    age: 24,
    hometown: "Ayala Alabang (Ilang-Ilang)",
    photoUrl: "", // demonstrate fallback placeholder
    isStarter: false,
    isActive: true,
  },
  {
    id: "p-titans-8",
    teamId: "team-titans",
    jerseyNumber: 8,
    name: "Javi De Leon",
    firstName: "Javi",
    lastName: "De Leon",
    position: "SG",
    height: "6'1\"",
    weight: "180 lbs",
    age: 30,
    hometown: "Ayala Alabang (Palms District)",
    photoUrl: "", // demonstrate fallback placeholder
    isStarter: false,
    isActive: true,
  },
  {
    id: "p-titans-21",
    teamId: "team-titans",
    jerseyNumber: 21,
    name: "Manny Bautista",
    firstName: "Manny",
    lastName: "Bautista",
    position: "PF",
    height: "6'4\"",
    weight: "215 lbs",
    age: 33,
    hometown: "Ayala Alabang (Banyan)",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    isStarter: false,
    isActive: true,
  },
  {
    id: "p-titans-99",
    teamId: "team-titans",
    jerseyNumber: 99,
    name: "EJ Villanueva",
    firstName: "EJ",
    lastName: "Villanueva",
    position: "C",
    height: "6'5\"",
    weight: "230 lbs",
    age: 32,
    hometown: "Ayala Alabang (Macopa)",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
    isStarter: false,
    isActive: true,
  },

  // --- VIPERS ROSTER ---
  {
    id: "p-vipers-24",
    teamId: "team-vipers",
    jerseyNumber: 24,
    name: "Christian Tan",
    firstName: "Christian",
    lastName: "Tan",
    position: "SG",
    height: "6'3\"",
    weight: "195 lbs",
    age: 27,
    hometown: "Ayala Alabang (San Juanico)",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-vipers-5",
    teamId: "team-vipers",
    jerseyNumber: 5,
    name: "Renzo Cruz",
    firstName: "Renzo",
    lastName: "Cruz",
    position: "PG",
    height: "5'10\"",
    weight: "170 lbs",
    age: 25,
    hometown: "Ayala Alabang (Luzon Drive)",
    photoUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-vipers-12",
    teamId: "team-vipers",
    jerseyNumber: 12,
    name: "Kenji Takahashi",
    firstName: "Kenji",
    lastName: "Takahashi",
    position: "SF",
    height: "6'2\"",
    weight: "188 lbs",
    age: 28,
    hometown: "Ayala Alabang (Mindanao Ave)",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-vipers-33",
    teamId: "team-vipers",
    jerseyNumber: 33,
    name: "Paolo Soriano",
    firstName: "Paolo",
    lastName: "Soriano",
    position: "PF",
    height: "6'5\"",
    weight: "220 lbs",
    age: 30,
    hometown: "Ayala Alabang (Bicol Drive)",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-vipers-42",
    teamId: "team-vipers",
    jerseyNumber: 42,
    name: "Alex Petrovic",
    firstName: "Alex",
    lastName: "Petrovic",
    position: "C",
    height: "6'7\"",
    weight: "240 lbs",
    age: 32,
    hometown: "Ayala Alabang (Country Club Enclave)",
    photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80",
    isStarter: true,
    isActive: true,
  },
  {
    id: "p-vipers-9",
    teamId: "team-vipers",
    jerseyNumber: 9,
    name: "Mark Gomez",
    firstName: "Mark",
    lastName: "Gomez",
    position: "SG",
    height: "6'0\"",
    weight: "178 lbs",
    age: 26,
    hometown: "Ayala Alabang (Cuenca)",
    photoUrl: "", // fallback placeholder
    isStarter: false,
    isActive: true,
  },
  {
    id: "p-vipers-18",
    teamId: "team-vipers",
    jerseyNumber: 18,
    name: "Carlo Mendoza",
    firstName: "Carlo",
    lastName: "Mendoza",
    position: "SF",
    height: "6'1\"",
    weight: "185 lbs",
    age: 29,
    hometown: "Ayala Alabang (Narra)",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    isStarter: false,
    isActive: true,
  },
  {
    id: "p-vipers-0",
    teamId: "team-vipers",
    jerseyNumber: 0,
    name: "Luigi Sy",
    firstName: "Luigi",
    lastName: "Sy",
    position: "PG",
    height: "5'8\"",
    weight: "160 lbs",
    age: 23,
    hometown: "Ayala Alabang (Acacia)",
    photoUrl: "", // fallback placeholder
    isStarter: false,
    isActive: true,
  },
];

export const INITIAL_GAMES: Game[] = [
  {
    id: "game-live-101",
    leagueId: "d2l-s10",
    season: "Season 10 - 2026",
    homeTeamId: "team-titans",
    awayTeamId: "team-vipers",
    homeScore: 68,
    awayScore: 64,
    quarter: "Q3",
    timeRemainingSeconds: 378, // 06:18
    isClockRunning: true,
    status: "live",
    scheduledAt: "2026-09-26T19:30:00+08:00",
    venue: "Ayala Alabang Village Main Gym - Court 1",
    homeFouls: 3,
    awayFouls: 4,
    homeTimeouts: 2,
    awayTimeouts: 3,
    possession: "home",
    officials: ["R. Fernandez (Crew Chief)", "J. Laurel (Referee)", "M. Dizon (Umpire)"],
    quarterScores: {
      home: { Q1: 22, Q2: 24, Q3: 22, Q4: 0 },
      away: { Q1: 20, Q2: 25, Q3: 19, Q4: 0 },
    },
  },
  {
    id: "game-past-100",
    leagueId: "d2l-s10",
    season: "Season 10 - 2026",
    homeTeamId: "team-knights",
    awayTeamId: "team-ballers",
    homeScore: 82,
    awayScore: 78,
    quarter: "Q4",
    timeRemainingSeconds: 0,
    isClockRunning: false,
    status: "final",
    scheduledAt: "2026-09-25T18:00:00+08:00",
    venue: "Ayala Alabang Village Main Gym - Court 1",
    homeFouls: 5,
    awayFouls: 6,
    homeTimeouts: 1,
    awayTimeouts: 0,
    possession: "neutral",
    officials: ["R. Fernandez", "E. Valenzuela"],
    quarterScores: {
      home: { Q1: 18, Q2: 22, Q3: 20, Q4: 22 },
      away: { Q1: 21, Q2: 17, Q3: 24, Q4: 16 },
    },
  },
  {
    id: "game-upcoming-102",
    leagueId: "d2l-s10",
    season: "Season 10 - 2026",
    homeTeamId: "team-aces",
    awayTeamId: "team-heat",
    homeScore: 0,
    awayScore: 0,
    quarter: "Q1",
    timeRemainingSeconds: 600,
    isClockRunning: false,
    status: "scheduled",
    scheduledAt: "2026-09-27T17:00:00+08:00",
    venue: "Cuenca Community Center Court",
    homeFouls: 0,
    awayFouls: 0,
    homeTimeouts: 4,
    awayTimeouts: 4,
    possession: "neutral",
    officials: ["J. Laurel", "M. Dizon"],
    quarterScores: {
      home: { Q1: 0, Q2: 0, Q3: 0, Q4: 0 },
      away: { Q1: 0, Q2: 0, Q3: 0, Q4: 0 },
    },
  },
  {
    id: "game-upcoming-103",
    leagueId: "d2l-s10",
    season: "Season 10 - 2026",
    homeTeamId: "team-kings",
    awayTeamId: "team-gunners",
    homeScore: 0,
    awayScore: 0,
    quarter: "Q1",
    timeRemainingSeconds: 600,
    isClockRunning: false,
    status: "scheduled",
    scheduledAt: "2026-09-28T19:00:00+08:00",
    venue: "Ayala Alabang Village Main Gym - Court 2",
    homeFouls: 0,
    awayFouls: 0,
    homeTimeouts: 4,
    awayTimeouts: 4,
    possession: "neutral",
    officials: ["R. Fernandez", "M. Dizon"],
    quarterScores: {
      home: { Q1: 0, Q2: 0, Q3: 0, Q4: 0 },
      away: { Q1: 0, Q2: 0, Q3: 0, Q4: 0 },
    },
  },
];

export const INITIAL_STAT_EVENTS: StatEvent[] = [
  {
    id: "evt-1",
    gameId: "game-live-101",
    teamId: "team-titans",
    playerId: "p-titans-34",
    quarter: "Q1",
    gameClock: "09:42",
    statType: "2PT_MAKE",
    points: 2,
    timestamp: Date.now() - 3600000,
    synced: true,
    staffName: "Dave Santos",
    staffRole: "staff",
    notes: "Hook shot in paint",
  },
  {
    id: "evt-2",
    gameId: "game-live-101",
    teamId: "team-titans",
    playerId: "p-titans-7",
    quarter: "Q1",
    gameClock: "09:42",
    statType: "AST",
    points: 0,
    timestamp: Date.now() - 3600000 + 100,
    synced: true,
    staffName: "Dave Santos",
    staffRole: "staff",
  },
  {
    id: "evt-3",
    gameId: "game-live-101",
    teamId: "team-vipers",
    playerId: "p-vipers-24",
    quarter: "Q1",
    gameClock: "09:15",
    statType: "3PT_MAKE",
    points: 3,
    timestamp: Date.now() - 3500000,
    synced: true,
    staffName: "Dave Santos",
    staffRole: "staff",
  },
  {
    id: "evt-4",
    gameId: "game-live-101",
    teamId: "team-titans",
    playerId: "p-titans-23",
    quarter: "Q1",
    gameClock: "08:40",
    statType: "STL",
    points: 0,
    timestamp: Date.now() - 3400000,
    synced: true,
    staffName: "Marcus Alcantara",
    staffRole: "admin",
  },
  {
    id: "evt-5",
    gameId: "game-live-101",
    teamId: "team-vipers",
    playerId: "p-vipers-5",
    quarter: "Q1",
    gameClock: "08:40",
    statType: "TO",
    points: 0,
    timestamp: Date.now() - 3400000 + 50,
    synced: true,
    staffName: "Marcus Alcantara",
    staffRole: "admin",
  },
  {
    id: "evt-6",
    gameId: "game-live-101",
    teamId: "team-titans",
    playerId: "p-titans-34",
    quarter: "Q3",
    gameClock: "06:18",
    statType: "DREB",
    points: 0,
    timestamp: Date.now() - 200000,
    synced: true,
    staffName: "Marcus Alcantara",
    staffRole: "admin",
    notes: "Defensive rebound off Christian Tan 3PT miss",
  },
  {
    id: "evt-7",
    gameId: "game-live-101",
    teamId: "team-titans",
    playerId: "p-titans-23",
    quarter: "Q3",
    gameClock: "06:05",
    statType: "3PT_MAKE",
    points: 3,
    timestamp: Date.now() - 150000,
    synced: true,
    staffName: "Dave Santos",
    staffRole: "staff",
    notes: "Corner triple",
  },
];
